### PR TITLE
add size check to avatar

### PR DESCRIPTION
**Pull request by 0i8**
sometimes servers will have users experience a "413 Request Entity Too Large" error because we don't currently handle big image files

### CODE REVIEW

**Comment by 7ez** [comment]
its nginx who checks it not quart though

**Comment by 0i8** [comment]
> its nginx who checks it not quart though

regardless we still don't handle it properly in the frontend

**Comment by 7ez** [comment]
also why arent you putting max image size in config file

**Comment by 0i8** [comment]
i forget that guweb uses a config.py file instead of a .env file

**Review by cmyui — CHANGES_REQUESTED** [review]
looks good to me - but should be moved to config.py

can merge after that

**Comment by 0i8** [comment]
satisfactory?

**Review by cmyui — APPROVED** [review]
thanks for the pr!

**Comment by 0i8** [comment]
i cannot believe i did that

**Comment by 0i8** [comment]
that is embarassing

**Pull request merged**
