### PR TITLE
redirect for osu change avatar button

### PR DESCRIPTION
**Pull request by ledlamp**
not tested pls verify validity

combine with 185644f5998c73a92215dc7bf4e6ef2a92a5c2bf

### CODE REVIEW

**Comment by Varkaria** [comment]
???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by ledlamp** [comment]
wat

**Comment by ledlamp** [comment]
move redirect from nginx to app

**Comment by Varkaria** [comment]
it's that's for switcher user right?

**Comment by ledlamp** [comment]
no it's for the change avatar button in osu, it opens a browser to /home/account/edit

**Comment by Varkaria** [comment]
ohh i get that

**Comment by ledlamp** [comment]
ok

**Pull request merged**
